[project]
name = "find-my-next-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "homeharvest",
    "folium",
    "pandas",
    "jupyter",
    "ipykernel",
]
